"""Add file metadata table with unique constraint

Revision ID: 9ddd293b66b0
Revises: 
Create Date: 2025-12-31 16:41:38.343857

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9ddd293b66b0'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('unique_file_per_user_version', 'files', ['user_id', 'filename', 'folder', 'version'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('unique_file_per_user_version', 'files', type_='unique')
    # ### end Alembic commands ###
